name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [RiotGamesServers, ChinaServer]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 添加 MSBuild 到 PATH
        uses: microsoft/setup-msbuild@v2

      - name: 构建项目
        shell: cmd
        run: msbuild R3nzSkin\R3nzSkin.vcxproj /p:Platform=x64 /p:Configuration=${{ matrix.configuration }}
