name: Build with MSBuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 MSBuild 环境
        uses: microsoft/setup-msbuild@v2

      - name: 构建项目
        run: |
          msbuild R3nzSkin.vcxproj /p:Configuration=Release /p:Platform=x64 /m
