name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v15.9'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: [RiotGamesServers, ChinaServer]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 MSBuild 环境
        uses: microsoft/setup-msbuild@v2

      - name: 构建项目
        run: |
          msbuild R3nzSkin\R3nzSkin.vcxproj /p:Platform=x64 /p:Configuration=${{ matrix.configuration }}

      - name: 打包构建产物
        run: |
          Compress-Archive -Path R3nzSkin\Release\* -DestinationPath R3nzSkin\${{ matrix.configuration }}.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.configuration }}
          path: R3nzSkin\${{ matrix.configuration }}.zip

  release:
    runs-on: windows-2022
    needs: build
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 创建 Git 标签
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: 创建 Release 并上传资产
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
