name: Publish HID.dll to Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v1.0.0)'
        required: true


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create ZIP Package
      run: |
        mkdir output
        # cp ChinaServer/HID.dll output/
        # cd ChinaServer/HID.dll ChinaServer/R3nzSkin.dll
        mv ChinaServer/HID.dll ChinaServer/R3nzSkin.dll
        zip -r R3nzSkin.zip ChinaServer/

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        files: R3nzSkin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
